### list packages 
GET http://cmcqa.futuredial.com/api/listpkgs/
    ?type=deviceprofile
    &solutionid=45


### cmc first download
POST http://cmcqa.futuredial.com/ws/update/
Content-Type: application/json

{
  "client": {
    "company": 1,
    "solutionid": 45,
    "productid": 55
  },
  "sync": {
    "status": {
      "framework": {
        "version": "",
        "filelist": []
      },
      "phonedll": {
        "filelist": [],
        "deletelist": []
      },
      "driver": {
        "filelist": [],
        "deletelist": []
      },
      "prl": {
        "filelist": [],
        "deletelist": []
      },
      "phonetips": {
        "filelist": [],
        "deletelist": []
      },
      "firmware": {
        "filelist": [],
        "deletelist": []
      },
      "deviceprofile": {
        "filelist": [],
        "deletelist": []
      }
    }
  },
  "protocol": "2.0"
}
