### ps.futuredial.com api
GET https://ps.futuredial.com/profiles/clients/_find
  ?criteria={"_id": "521eb3dd-47f0-40ef-9b54-30466dfe6cc7"}
Content-Type: application/json


### ps.futuredial.com api
GET https://ps.futuredial.com/profiles/clients/_find
  ?criteria={"_id": "75c10cc6-92c3-49f6-be55-fd0f5891a4e0"}
Content-Type: application/json


### list packages 
GET http://cmcqa.futuredial.com/api/listpkgs/
    ?type=deviceprofile    
    &solutionid=45


### list firmware packages 
GET http://cmcqa.futuredial.com/api/listpkgs/
    ?type=firmware    
    &solutionid=45


### cmc first download
POST http://cmcqa.futuredial.com/ws/update/
Content-Type: application/json

< ./empty_request.json


### cmc get wsid
POST http://cmcqa.futuredial.com/api/workstationcheckin/
Content-Type: application/json

{"client":{"macaddr":"E7801EFE-110E-4FC6-99A0-A91F0B13DBD3"}}


### cmc check in
POST http://cmcqa.futuredial.com/ws/update/
Content-Type: application/json

< ./checkin.json


### list packages 
GET http://cmcqa.futuredial.com/api/listpkgs/
    ?solutionid=45
    &type=prl

###    
GET http://cmcqa.futuredial.com/api/pkginfo/
    ?solutionid=45
    &type=deviceprofile
    &pkgid=samsung-galaxy-black-1.0

